node_types:
  cloudify.agent_code.example:
    derived_from: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          implementation: example.agent_code.tasks.write_to_file # example - name of plugin at the line 10, agent_code - packages in setup.py

  # cloudify.example.tick:
  #   derived_from: cloudify.nodes.ApplicationServer
  #   interfaces:
  #     foo:
  #       tick:
  #         implementation: example.agent_code.tasks.tick
  #         inputs:
  #           test_time:
  #             default: 30
  #       tick_true:
  #         implementation: example.agent_code.tasks.tick_true
  #         inputs:
  #           test_time:
  #             default: 30
  #       tick_false:
  #         implementation: example.agent_code.tasks.tick_false
  #         inputs:
  #           test_time:
  #             default: 30

plugins:
  example:
    executor: host_agent
    package_name: 'cloudify-plugin-example'
    source: cloudify-plugin-example
    package_version: '0.0.1'
